import type { GearItem } from "./types";

export const GEAR_CATALOG: GearItem[] = [
  // Common weapons / armor
  {
    id: "iron-sword",
    name: "Iron Longsword",
    blurb: "A hold-forged blade, honest and plain.",
    tier: "common",
    slot: "weapon",
    power: 6,
    tags: ["melee"],
  },
  {
    id: "hunting-bow",
    name: "Hunting Bow",
    blurb: "Yew and sinew — good for deer and goblins alike.",
    tier: "common",
    slot: "weapon",
    power: 5,
    tags: ["ranged", "bow"],
  },
  {
    id: "oak-staff",
    name: "Oak Staff",
    blurb: "A traveler's stick that hums faintly at ley lines.",
    tier: "common",
    slot: "weapon",
    power: 4,
    tags: ["staff", "arcane"],
  },
  {
    id: "leather-cap",
    name: "Leather Cap",
    blurb: "Keeps rain and glancing blades at bay.",
    tier: "common",
    slot: "head",
    armor: 1,
    tags: ["light"],
  },
  {
    id: "hide-jerkin",
    name: "Hide Jerkin",
    blurb: "Soft hide of the northern woods.",
    tier: "common",
    slot: "chest",
    armor: 2,
    tags: ["light"],
  },
  {
    id: "travel-gloves",
    name: "Travel Gloves",
    blurb: "Worn leather for rope and bowstring.",
    tier: "common",
    slot: "hands",
    armor: 1,
    tags: ["light"],
  },
  {
    id: "wool-trousers",
    name: "Wool Trousers",
    blurb: "Warm enough for Misty Hill roads.",
    tier: "common",
    slot: "legs",
    armor: 1,
    tags: ["light"],
  },
  {
    id: "wood-shield",
    name: "Wooden Shield",
    blurb: "Painted with a crude wolf — better than nothing.",
    tier: "common",
    slot: "offhand",
    armor: 2,
    tags: ["shield"],
  },
  {
    id: "copper-ring",
    name: "Copper Ring",
    blurb: "A keepsake from home.",
    tier: "common",
    slot: "accessory",
    tags: ["trinket"],
  },
  // Magic
  {
    id: "frostbite-blade",
    name: "Frostbite Blade",
    blurb: "Steel rimed with everlasting chill.",
    tier: "magic",
    slot: "weapon",
    power: 12,
    tags: ["melee", "frost"],
  },
  {
    id: "elven-bow",
    name: "Elven Longbow",
    blurb: "Light as moonbeam, true as oath.",
    tier: "magic",
    slot: "weapon",
    power: 11,
    tags: ["ranged", "bow", "elven"],
  },
  {
    id: "staff-of-embers",
    name: "Staff of Embers",
    blurb: "A core of banked dragon-coal.",
    tier: "magic",
    slot: "weapon",
    power: 13,
    tags: ["staff", "fire"],
  },
  {
    id: "mail-of-rivendell",
    name: "Mail of Rivendell Roads",
    blurb: "Rings that sing faintly when danger nears.",
    tier: "magic",
    slot: "chest",
    armor: 6,
    tags: ["medium", "elven"],
  },
  {
    id: "amulet-of-warding",
    name: "Amulet of Warding",
    blurb: "A soft ward against hex and fang.",
    tier: "magic",
    slot: "accessory",
    armor: 2,
    tags: ["ward"],
  },
  // Legendary
  {
    id: "sword-of-the-chronicle",
    name: "Sword of the Chronicle",
    blurb: "Forged for three names and three hounds — Justin, Rusty, Elisha.",
    tier: "legendary",
    slot: "weapon",
    power: 28,
    tags: ["melee", "legendary", "party"],
  },
  {
    id: "crown-of-ash",
    name: "Crown of Ash",
    blurb: "A circlet of cooled dragon-glass. Heavy with choice.",
    tier: "legendary",
    slot: "head",
    armor: 4,
    power: 4,
    tags: ["legendary", "crown"],
  },
  {
    id: "cloak-of-fellowship",
    name: "Cloak of Fellowship",
    blurb: "Woven so three walkers never lose each other's trail.",
    tier: "legendary",
    slot: "accessory",
    armor: 3,
    tags: ["legendary", "party"],
  },
  // Consumables
  {
    id: "healing-potion",
    name: "Healing Potion",
    blurb: "Red vial of mountain herbs.",
    tier: "common",
    slot: "consumable",
    heal: 25,
    tags: ["potion", "heal"],
  },
  {
    id: "mana-draught",
    name: "Mana Draught",
    blurb: "Blue mist in a crystal phial.",
    tier: "magic",
    slot: "consumable",
    tags: ["potion", "mana"],
  },
  {
    id: "trail-rations",
    name: "Trail Rations",
    blurb: "Dried meat, hard bread, a strip of cheese.",
    tier: "common",
    slot: "consumable",
    heal: 8,
    cookBonus: 1,
    tags: ["food"],
  },
  {
    id: "hound-treat",
    name: "Hound's Treat",
    blurb: "Dried liver — your companion's favorite.",
    tier: "common",
    slot: "consumable",
    tags: ["dog", "food"],
  },
];

export function getGear(id: string): GearItem | undefined {
  return GEAR_CATALOG.find((g) => g.id === id);
}

export const STARTER_GEAR_BY_CLASS: Record<string, string[]> = {
  warrior: ["iron-sword", "wood-shield", "hide-jerkin", "healing-potion", "trail-rations", "hound-treat"],
  ranger: ["hunting-bow", "leather-cap", "hide-jerkin", "healing-potion", "trail-rations", "hound-treat"],
  mage: ["oak-staff", "copper-ring", "wool-trousers", "mana-draught", "healing-potion", "hound-treat"],
  rogue: ["iron-sword", "leather-cap", "travel-gloves", "healing-potion", "trail-rations", "hound-treat"],
  paladin: ["iron-sword", "wood-shield", "hide-jerkin", "healing-potion", "trail-rations", "hound-treat"],
};
