import type { MealTemplate } from "./research-types";

/**
 * Educational surplus-meal templates for healthy weight gain (adult man).
 * Calorie/protein numbers are approximate game-facing estimates, not lab assays.
 */
export const MEALS: MealTemplate[] = [
  {
    id: "oat-power-bowl",
    name: "Oat Power Bowl",
    blurb:
      "Steel-cut oats cooked in milk, topped with Greek yogurt, berries, peanut butter, and a drizzle of honey — slow carbs plus sticky protein for a surplus morning.",
    slot: "breakfast",
    caloriesApprox: 720,
    proteinGramsApprox: 38,
    tags: ["surplus", "high-protein", "whole-food"],
    ingredients: [
      "steel-cut oats",
      "whole milk",
      "Greek yogurt",
      "mixed berries",
      "natural peanut butter",
      "honey",
      "chia seeds",
    ],
    questHook: "Quest: Load the morning furnace before the dungeon opens.",
  },
  {
    id: "egg-avocado-toast-stack",
    name: "Egg & Avocado Toast Stack",
    blurb:
      "Thick sourdough piled with smashed avocado, scrambled eggs, and cottage cheese on the side — dense without feeling like a food coma.",
    slot: "breakfast",
    caloriesApprox: 650,
    proteinGramsApprox: 42,
    tags: ["surplus", "high-protein", "whole-food"],
    ingredients: [
      "sourdough bread",
      "eggs",
      "avocado",
      "cottage cheese",
      "olive oil",
      "cherry tomatoes",
      "black pepper",
    ],
    questHook: "Side quest: Stack the tower of toast; claim the protein crown.",
  },
  {
    id: "chicken-rice-broccoli-plate",
    name: "Chicken, Rice & Broccoli Plate",
    blurb:
      "Classic mass-gain plate: grilled chicken thighs, jasmine rice, roasted broccoli, and olive oil. Boring in the best way — repeatable and trackable.",
    slot: "lunch",
    caloriesApprox: 780,
    proteinGramsApprox: 55,
    tags: ["surplus", "high-protein", "meal-prep"],
    ingredients: [
      "chicken thighs",
      "jasmine rice",
      "broccoli",
      "olive oil",
      "garlic",
      "soy sauce",
      "sesame seeds",
    ],
    questHook: "Daily raid: Clear the plate; bank the surplus XP.",
  },
  {
    id: "turkey-burrito-bowl",
    name: "Turkey Burrito Bowl",
    blurb:
      "Lean ground turkey over brown rice with black beans, salsa, cheese, and guacamole — fiber, protein, and calorie density in one bowl.",
    slot: "lunch",
    caloriesApprox: 820,
    proteinGramsApprox: 52,
    tags: ["surplus", "high-protein", "whole-food"],
    ingredients: [
      "ground turkey",
      "brown rice",
      "black beans",
      "cheddar",
      "guacamole",
      "salsa",
      "romaine",
      "sour cream",
    ],
    questHook: "Quest update: Assemble the bowl; don't leave XP on the table.",
  },
  {
    id: "tuna-wrap-plate",
    name: "Tuna Wrap Plate",
    blurb:
      "Tuna mixed with Greek yogurt in a whole-wheat wrap, plus a side of hummus and crackers — lunch that travels well and still hits protein targets.",
    slot: "lunch",
    caloriesApprox: 700,
    proteinGramsApprox: 50,
    tags: ["surplus", "high-protein", "meal-prep"],
    ingredients: [
      "canned tuna",
      "Greek yogurt",
      "whole-wheat wrap",
      "spinach",
      "hummus",
      "whole-grain crackers",
      "cucumber",
    ],
    questHook: "Travel quest: Pack the wrap; don't miss the midday checkpoint.",
  },
  {
    id: "salmon-potato-asparagus",
    name: "Salmon, Potato & Asparagus",
    blurb:
      "Oven salmon with buttered baby potatoes and asparagus. Omega-3s meet calorie-friendly carbs for a dinner that still supports training recovery.",
    slot: "dinner",
    caloriesApprox: 850,
    proteinGramsApprox: 48,
    tags: ["surplus", "high-protein", "omega-3"],
    ingredients: [
      "salmon fillet",
      "baby potatoes",
      "asparagus",
      "butter",
      "lemon",
      "olive oil",
      "dill",
    ],
    questHook: "Boss dinner: Feed the regen bar after the heavy sets.",
  },
  {
    id: "beef-stir-fry-noodles",
    name: "Beef Stir-Fry Noodles",
    blurb:
      "Sirloin strips with mixed veggies over egg noodles and a light sauce — higher calories from noodles and oil, still built around protein.",
    slot: "dinner",
    caloriesApprox: 900,
    proteinGramsApprox: 50,
    tags: ["surplus", "high-protein", "calorie-dense"],
    ingredients: [
      "sirloin beef",
      "egg noodles",
      "bell peppers",
      "snap peas",
      "onion",
      "garlic",
      "soy sauce",
      "sesame oil",
    ],
    questHook: "Night raid: Wok the wok; claim surplus loot.",
  },
  {
    id: "pasta-meat-sauce",
    name: "Pasta with Meat Sauce",
    blurb:
      "Whole-wheat pasta with a beef-and-turkey meat sauce, Parmesan, and a side salad — comfort food still aimed at training fuel, not chaos calories.",
    slot: "dinner",
    caloriesApprox: 880,
    proteinGramsApprox: 46,
    tags: ["surplus", "high-protein", "calorie-dense"],
    ingredients: [
      "whole-wheat pasta",
      "lean ground beef",
      "ground turkey",
      "tomato sauce",
      "onion",
      "garlic",
      "Parmesan",
      "mixed greens",
    ],
    questHook: "Feast quest: Twirl the noodles; seal tonight's surplus.",
  },
  {
    id: "greek-yogurt-parfait",
    name: "Greek Yogurt Parfait",
    blurb:
      "Full-fat Greek yogurt layered with granola, banana, and almond butter — easy snack that pads protein without a second kitchen shift.",
    slot: "snack",
    caloriesApprox: 520,
    proteinGramsApprox: 32,
    tags: ["surplus", "high-protein", "convenient"],
    ingredients: [
      "full-fat Greek yogurt",
      "granola",
      "banana",
      "almond butter",
      "honey",
      "cinnamon",
    ],
    questHook: "Mini quest: Layer the parfait; pocket mid-day XP.",
  },
  {
    id: "trail-mix-apple",
    name: "Trail Mix & Apple",
    blurb:
      "A measured handful of nuts and dried fruit with a crisp apple — portable calories that don't require cooking when the schedule gets chaotic.",
    slot: "snack",
    caloriesApprox: 450,
    proteinGramsApprox: 12,
    tags: ["surplus", "convenient", "calorie-dense"],
    ingredients: [
      "almonds",
      "cashews",
      "pumpkin seeds",
      "dried cranberries",
      "dark chocolate chips",
      "apple",
    ],
    questHook: "Field ration: Grab the pouch; keep the surplus streak alive.",
  },
  {
    id: "mass-builder-shake",
    name: "Mass-Builder Shake",
    blurb:
      "Whey, milk, oats, banana, and peanut butter blended smooth — liquid surplus when chewing another plate feels like a side boss.",
    slot: "shake",
    caloriesApprox: 680,
    proteinGramsApprox: 45,
    tags: ["surplus", "high-protein", "convenient", "post-workout"],
    ingredients: [
      "whey protein",
      "whole milk",
      "rolled oats",
      "banana",
      "peanut butter",
      "ice",
    ],
    questHook: "Potion craft: Blend the elixir; refill the growth meter.",
  },
  {
    id: "cottage-berry-shake",
    name: "Cottage Berry Shake",
    blurb:
      "Cottage cheese, frozen berries, milk, and a scoop of whey — high protein, moderate calories, great as a lighter second shake day.",
    slot: "shake",
    caloriesApprox: 480,
    proteinGramsApprox: 48,
    tags: ["surplus", "high-protein", "convenient"],
    ingredients: [
      "cottage cheese",
      "frozen berries",
      "whey protein",
      "2% milk",
      "vanilla extract",
      "ice",
    ],
    questHook: "Side potion: Sip the pink elixir; stack recovery XP.",
  },
  {
    id: "drive-thru-double-combo",
    name: "Drive-Thru Double Combo",
    blurb:
      "Double burger, large fries, and a soda — big calories, weak protein density, and a crash waiting later. The engine can soft-penalize this junk trap.",
    slot: "lunch",
    caloriesApprox: 1450,
    proteinGramsApprox: 28,
    tags: ["junk", "calorie-dense", "poorly-balanced"],
    ingredients: [
      "double cheeseburger",
      "large fries",
      "soda",
      "ketchup packets",
    ],
    questHook: "Trap alert: Easy loot, rotten buffs — the surplus is dirty.",
  },
];
